name: Backport
on:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Create backport PRs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: >
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v2
      - name: Create backport PRs
        uses: zeebe-io/backport-action@v0.0.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_workspace: ${{ github.workspace }}
